---
title: "Bikeshare"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readr)
library(ggplot2)
library(dplyr)
library(lubridate)
```

```{r load_data, include = FALSE}
trips_df <- read_csv('http://s3.amazonaws.com/assets.datacamp.com/production/course_5875/datasets/sanfran_bikeshare_joined_oneday.csv')
```

Overview
=================================================================

Column {data-width=750, .tabset}
-----------------------------------------------------------------------

### Chart A

```{r}

```

### Chart B

```{r plot1}

trips_df %>%
  mutate(Hour = hour(start_date)) %>%
  group_by(Hour) %>%
  summarize(`Trips Started` = n()) %>%
  ggplot(aes(x = Hour, y = `Trips Started`)) +
  theme_bw() +
  geom_bar(stat = 'identity')

```

Column {data-width=250}
-----------------------------------------------------------------------

### Chart C

```{r}

```

### Chart D

```{r}

```

Details
=================================================================

### Chart E

```{r}

```

Details {data-navmenu=More}
=====================================

### Chart AA

```{r}

```

Data {data-navmenu=More}
=====================================

### Chart BB

```{r}

```
