---
title: "Bike Shares Daily"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}
library(flexdashboard)
library(readr)
library(leaflet)
library(DT)
library(tidyverse)
library(lubridate)
library(plotly)

trips_df <- read_csv('https://assets.datacamp.com/production/repositories/1448/datasets/1f12031000b09ad096880bceb61f6ca2fd95e2eb/sanfran_bikeshare_joined_oneday.csv') %>%
  mutate(duration_min = duration_sec / 60) %>%
  filter(duration_min <= 8 * 60) # filtering out trips over 8 hours as suspicious

```

Column {data-width=450}
-----------------------------------------------------------------------

### Origins

```{r}

renderLeaflet({
  trips_df %>%
    rename(latitude = start_latitude,
           longitude = start_longitude) %>%
    group_by(start_station_id, latitude, longitude) %>%
    count() %>%
    leaflet() %>%
    addTiles() %>%
    addCircles(radius = ~n)
})

```

Column {data-width=350}
-----------------------------------------------------------------------

### Total Trips

```{r}

renderValueBox({
  valueBox(prettyNum(trips_df %>%
                       nrow(), big.mark = ','), 
           icon = 'fa-bicycle')
})

```

### Trip Durations

```{r}
sliderInput("duration_bin", label = "Select # of minutes to bin trip durations:",
min = 1, max = 15, value = 5, step = 1)

renderPlot({trips_df %>%
  mutate(`Trip Duration (min)` = duration_sec / 60) %>%
  ggplot(aes(x = `Trip Duration (min)`)) +
  theme_bw() +
  geom_histogram(binwidth = input$duration_bin) +
  ylab('# Trips')
})


```


